import Head from "next/head";
import Layout from "../components/layout";
import Intro from "./sections/intro";
import Main from "./sections/main";
import Viewer from "./sections/viewer";
import Chart from "./sections/chart";

export default function Home() {
  return (
    <div>
      <Head>
        <title>1Q WEDDING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/hana-1q-logo-0.png" />
      </Head>
      <Layout>
        <Main />
        {/* <Intro />
        <Viewer /> */}
        {/* <Chart /> */}
      </Layout>
    </div>
  );
}
