import Head from "next/head";
import Layout from "../components/layout";
import Canvas from "./sections/canvas";
import Intro from "./sections/intro";
import Main from "./sections/main";
import Recorder from "./sections/recorder";
import Viewer from "./sections/viewer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>1Q WEDDING</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.png" />
      </Head>
      <Layout>
        <Main />
        <Intro />
        <Canvas />
        <Viewer />
        <Recorder />
      </Layout>
    </div>
  );
}
